// Global variable for country/timezone data
const countryTimezonesData = [
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "America/New_York", "city": "Nova Iorque" },
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "America/Chicago", "city": "Chicago" },
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "America/Denver", "city": "Denver" },
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "America/Los_Angeles", "city": "Los Angeles" },
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "America/Anchorage", "city": "Anchorage" },
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "Pacific/Honolulu", "city": "Honolulu" },
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "America/Phoenix", "city": "Phoenix" },
    { "country_code": "US", "country_name": "Estados Unidos", "time_zone": "America/Detroit", "city": "Detroit" },
    { "country_code": "AU", "country_name": "Austrália", "time_zone": "Australia/Sydney", "city": "Sydney" },
    { "country_code": "AU", "country_name": "Austrália", "time_zone": "Australia/Melbourne", "city": "Melbourne" },
    { "country_code": "AU", "country_name": "Austrália", "time_zone": "Australia/Brisbane", "city": "Brisbane" },
    { "country_code": "AU", "country_name": "Austrália", "time_zone": "Australia/Perth", "city": "Perth" },
    { "country_code": "AU", "country_name": "Austrália", "time_zone": "Australia/Adelaide", "city": "Adelaide" },
    { "country_code": "AU", "country_name": "Austrália", "time_zone": "Australia/Hobart", "city": "Hobart" },
    { "country_code": "AU", "country_name": "Austrália", "time_zone": "Australia/Darwin", "city": "Darwin" },
    { "country_code": "ES", "country_name": "Espanha", "time_zone": "Europe/Madrid", "city": "Madri" },
    { "country_code": "ES", "country_name": "Espanha", "time_zone": "Atlantic/Canary", "city": "Ilhas Canárias" },
    { "country_code": "ES", "country_name": "Espanha", "time_zone": "Africa/Ceuta", "city": "Ceuta" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Europe/Moscow", "city": "Moscou" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Europe/Kaliningrad", "city": "Kaliningrado" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Yekaterinburg", "city": "Ecaterimburgo" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Omsk", "city": "Omsk" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Krasnoyarsk", "city": "Krasnoiarsk" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Irkutsk", "city": "Irkutsk" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Yakutsk", "city": "Iacutsk" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Vladivostok", "city": "Vladivostok" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Magadan", "city": "Magadan" },
    { "country_code": "RU", "country_name": "Rússia", "time_zone": "Asia/Kamchatka", "city": "Kamchatka" },
    { "country_code": "BR", "country_name": "Brasil", "time_zone": "America/Sao_Paulo", "city": "São Paulo" },
    { "country_code": "BR", "country_name": "Brasil", "time_zone": "America/Manaus", "city": "Manaus" },
    { "country_code": "BR", "country_name": "Brasil", "time_zone": "America/Noronha", "city": "Noronha" },
    { "country_code": "CA", "country_name": "Canadá", "time_zone": "America/Toronto", "city": "Toronto" },
    { "country_code": "CA", "country_name": "Canadá", "time_zone": "America/Vancouver", "city": "Vancouver" },
    { "country_code": "CA", "country_name": "Canadá", "time_zone": "America/Edmonton", "city": "Edmonton" },
    { "country_code": "CA", "country_name": "Canadá", "time_zone": "America/Winnipeg", "city": "Winnipeg" },
    { "country_code": "CA", "country_name": "Canadá", "time_zone": "America/Halifax", "city": "Halifax" },
    { "country_code": "CA", "country_name": "Canadá", "time_zone": "America/St_Johns", "city": "St. Johns" },
    { "country_code": "AD", "country_name": "Andorra", "time_zone": "Europe/Andorra", "city": "Andorra" },
    { "country_code": "AE", "country_name": "Emirados Árabes Unidos", "time_zone": "Asia/Dubai", "city": "Dubai" },
    { "country_code": "AF", "country_name": "Afeganistão", "time_zone": "Asia/Kabul", "city": "Cabul" },
    { "country_code": "AG", "country_name": "Antígua e Barbuda", "time_zone": "America/Antigua", "city": "Antígua" },
    { "country_code": "AI", "country_name": "Anguila", "time_zone": "America/Anguilla", "city": "Anguila" },
    { "country_code": "AL", "country_name": "Albânia", "time_zone": "Europe/Tirane", "city": "Tirana" },
    { "country_code": "AM", "country_name": "Armênia", "time_zone": "Asia/Yerevan", "city": "Yerevan" },
    { "country_code": "AO", "country_name": "Angola", "time_zone": "Africa/Luanda", "city": "Luanda" },
    { "country_code": "AQ", "country_name": "Antártida", "time_zone": "Antarctica/McMurdo", "city": "Estação McMurdo" },
    { "country_code": "AQ", "country_name": "Antártida", "time_zone": "Antarctica/Casey", "city": "Estação Casey" },
    { "country_code": "AQ", "country_name": "Antártida", "time_zone": "Antarctica/Davis", "city": "Estação Davis" },
    { "country_code": "AR", "country_name": "Argentina", "time_zone": "America/Argentina/Buenos_Aires", "city": "Buenos Aires" },
    { "country_code": "AS", "country_name": "Samoa Americana", "time_zone": "Pacific/Pago_Pago", "city": "Pago Pago" },
    { "country_code": "AT", "country_name": "Áustria", "time_zone": "Europe/Vienna", "city": "Viena" },
    { "country_code": "AW", "country_name": "Aruba", "time_zone": "America/Aruba", "city": "Aruba" },
    { "country_code": "AZ", "country_name": "Azerbaijão", "time_zone": "Asia/Baku", "city": "Baku" },
    { "country_code": "BA", "country_name": "Bósnia e Herzegovina", "time_zone": "Europe/Sarajevo", "city": "Sarajevo" },
    { "country_code": "BB", "country_name": "Barbados", "time_zone": "America/Barbados", "city": "Barbados" },
    { "country_code": "BD", "country_name": "Bangladesh", "time_zone": "Asia/Dhaka", "city": "Daca" },
    { "country_code": "BE", "country_name": "Bélgica", "time_zone": "Europe/Brussels", "city": "Bruxelas" },
    { "country_code": "BG", "country_name": "Bulgária", "time_zone": "Europe/Sofia", "city": "Sófia" },
    { "country_code": "BH", "country_name": "Bahrein", "time_zone": "Asia/Bahrain", "city": "Bahrein" },
    { "country_code": "BM", "country_name": "Bermudas", "time_zone": "Atlantic/Bermuda", "city": "Bermudas" },
    { "country_code": "BN", "country_name": "Brunei", "time_zone": "Asia/Brunei", "city": "Brunei" },
    { "country_code": "BO", "country_name": "Bolívia", "time_zone": "America/La_Paz", "city": "La Paz" },
    { "country_code": "BS", "country_name": "Bahamas", "time_zone": "America/Nassau", "city": "Nassau" },
    { "country_code": "BT", "country_name": "Butão", "time_zone": "Asia/Thimphu", "city": "Thimphu" },
    { "country_code": "BW", "country_name": "Botsuana", "time_zone": "Africa/Gaborone", "city": "Gaborone" },
    { "country_code": "BY", "country_name": "Bielorrússia", "time_zone": "Europe/Minsk", "city": "Minsk" },
    { "country_code": "BZ", "country_name": "Belize", "time_zone": "America/Belize", "city": "Belize" },
    { "country_code": "CD", "country_name": "República Democrática do Congo", "time_zone": "Africa/Kinshasa", "city": "Quinxassa" },
    { "country_code": "CF", "country_name": "República Centro-Africana", "time_zone": "Africa/Bangui", "city": "Bangui" },
    { "country_code": "CH", "country_name": "Suíça", "time_zone": "Europe/Zurich", "city": "Zurique" },
    { "country_code": "CI", "country_name": "Costa do Marfim", "time_zone": "Africa/Abidjan", "city": "Abidjan" },
    { "country_code": "CK", "country_name": "Ilhas Cook", "time_zone": "Pacific/Rarotonga", "city": "Rarotonga" },
    { "country_code": "CL", "country_name": "Chile", "time_zone": "America/Santiago", "city": "Santiago" },
    { "country_code": "CL", "country_name": "Chile", "time_zone": "Pacific/Easter", "city": "Ilha de Páscoa" },
    { "country_code": "CM", "country_name": "Camarões", "time_zone": "Africa/Douala", "city": "Douala" },
    { "country_code": "CN", "country_name": "China", "time_zone": "Asia/Shanghai", "city": "Xangai" },
    { "country_code": "CO", "country_name": "Colômbia", "time_zone": "America/Bogota", "city": "Bogotá" },
    { "country_code": "CR", "country_name": "Costa Rica", "time_zone": "America/Costa_Rica", "city": "Costa Rica" },
    { "country_code": "CU", "country_name": "Cuba", "time_zone": "America/Havana", "city": "Havana" },
    { "country_code": "CV", "country_name": "Cabo Verde", "time_zone": "Atlantic/Cape_Verde", "city": "Cabo Verde" },
    { "country_code": "CY", "country_name": "Chipre", "time_zone": "Asia/Nicosia", "city": "Nicósia" },
    { "country_code": "CZ", "country_name": "República Tcheca", "time_zone": "Europe/Prague", "city": "Praga" },
    { "country_code": "DE", "country_name": "Alemanha", "time_zone": "Europe/Berlin", "city": "Berlim" },
    { "country_code": "DK", "country_name": "Dinamarca", "time_zone": "Europe/Copenhagen", "city": "Copenhague" },
    { "country_code": "DO", "country_name": "República Dominicana", "time_zone": "America/Santo_Domingo", "city": "Santo Domingo" },
    { "country_code": "DZ", "country_name": "Argélia", "time_zone": "Africa/Algiers", "city": "Argel" },
    { "country_code": "EC", "country_name": "Equador", "time_zone": "America/Guayaquil", "city": "Guayaquil" },
    { "country_code": "EC", "country_name": "Equador", "time_zone": "Pacific/Galapagos", "city": "Galápagos" },
    { "country_code": "EE", "country_name": "Estônia", "time_zone": "Europe/Tallinn", "city": "Tallinn" },
    { "country_code": "EG", "country_name": "Egito", "time_zone": "Africa/Cairo", "city": "Cairo" },
    { "country_code": "FI", "country_name": "Finlândia", "time_zone": "Europe/Helsinki", "city": "Helsinque" },
    { "country_code": "FJ", "country_name": "Fiji", "time_zone": "Pacific/Fiji", "city": "Fiji" },
    { "country_code": "FK", "country_name": "Ilhas Malvinas", "time_zone": "Atlantic/Stanley", "city": "Stanley" },
    { "country_code": "FR", "country_name": "França", "time_zone": "Europe/Paris", "city": "Paris" },
    { "country_code": "GB", "country_name": "Reino Unido", "time_zone": "Europe/London", "city": "Londres" },
    { "country_code": "GE", "country_name": "Geórgia", "time_zone": "Asia/Tbilisi", "city": "Tbilisi" },
    { "country_code": "GF", "country_name": "Guiana Francesa", "time_zone": "America/Cayenne", "city": "Caiena" },
    { "country_code": "GH", "country_name": "Gana", "time_zone": "Africa/Accra", "city": "Acra" },
    { "country_code": "GL", "country_name": "Groenlândia", "time_zone": "America/Godthab", "city": "Nuuk" },
    { "country_code": "GR", "country_name": "Grécia", "time_zone": "Europe/Athens", "city": "Atenas" },
    { "country_code": "GT", "country_name": "Guatemala", "time_zone": "America/Guatemala", "city": "Guatemala" },
    { "country_code": "GY", "country_name": "Guiana", "time_zone": "America/Guyana", "city": "Guiana" },
    { "country_code": "HK", "country_name": "Hong Kong", "time_zone": "Asia/Hong_Kong", "city": "Hong Kong" },
    { "country_code": "HN", "country_name": "Honduras", "time_zone": "America/Tegucigalpa", "city": "Tegucigalpa" },
    { "country_code": "HR", "country_name": "Croácia", "time_zone": "Europe/Zagreb", "city": "Zagreb" },
    { "country_code": "HT", "country_name": "Haiti", "time_zone": "America/Port-au-Prince", "city": "Porto Príncipe" },
    { "country_code": "HU", "country_name": "Hungria", "time_zone": "Europe/Budapest", "city": "Budapeste" },
    { "country_code": "ID", "country_name": "Indonésia", "time_zone": "Asia/Jakarta", "city": "Jacarta" },
    { "country_code": "IE", "country_name": "Irlanda", "time_zone": "Europe/Dublin", "city": "Dublin" },
    { "country_code": "IL", "country_name": "Israel", "time_zone": "Asia/Jerusalem", "city": "Jerusalém" },
    { "country_code": "IN", "country_name": "Índia", "time_zone": "Asia/Kolkata", "city": "Calcutá" },
    { "country_code": "IQ", "country_name": "Iraque", "time_zone": "Asia/Baghdad", "city": "Bagdá" },
    { "country_code": "IR", "country_name": "Irã", "time_zone": "Asia/Tehran", "city": "Teerã" },
    { "country_code": "IS", "country_name": "Islândia", "time_zone": "Atlantic/Reykjavik", "city": "Reiquiavique" },
    { "country_code": "IT", "country_name": "Itália", "time_zone": "Europe/Rome", "city": "Roma" },
    { "country_code": "JM", "country_name": "Jamaica", "time_zone": "America/Jamaica", "city": "Jamaica" },
    { "country_code": "JO", "country_name": "Jordânia", "time_zone": "Asia/Amman", "city": "Amã" },
    { "country_code": "JP", "country_name": "Japão", "time_zone": "Asia/Tokyo", "city": "Tóquio" },
    { "country_code": "KE", "country_name": "Quênia", "time_zone": "Africa/Nairobi", "city": "Nairóbi" },
    { "country_code": "KG", "country_name": "Quirguistão", "time_zone": "Asia/Bishkek", "city": "Bisqueque" },
    { "country_code": "KH", "country_name": "Camboja", "time_zone": "Asia/Phnom_Penh", "city": "Phnom Penh" },
    { "country_code": "KI", "country_name": "Quiribati", "time_zone": "Pacific/Tarawa", "city": "Tarawa" },
    { "country_code": "KI", "country_name": "Quiribati", "time_zone": "Pacific/Kiritimati", "city": "Kiritimati" },
    { "country_code": "KP", "country_name": "Coreia do Norte", "time_zone": "Asia/Pyongyang", "city": "Pyongyang" },
    { "country_code": "KR", "country_name": "Coreia do Sul", "time_zone": "Asia/Seoul", "city": "Seul" },
    { "country_code": "KW", "country_name": "Kuwait", "time_zone": "Asia/Kuwait", "city": "Kuwait" },
    { "country_code": "KZ", "country_name": "Cazaquistão", "time_zone": "Asia/Almaty", "city": "Almaty" },
    { "country_code": "LB", "country_name": "Líbano", "time_zone": "Asia/Beirut", "city": "Beirute" },
    { "country_code": "LK", "country_name": "Sri Lanka", "time_zone": "Asia/Colombo", "city": "Colombo" },
    { "country_code": "LR", "country_name": "Libéria", "time_zone": "Africa/Monrovia", "city": "Monróvia" },
    { "country_code": "LT", "country_name": "Lituânia", "time_zone": "Europe/Vilnius", "city": "Vilnius" },
    { "country_code": "LU", "country_name": "Luxemburgo", "time_zone": "Europe/Luxembourg", "city": "Luxemburgo" },
    { "country_code": "LV", "country_name": "Letônia", "time_zone": "Europe/Riga", "city": "Riga" },
    { "country_code": "LY", "country_name": "Líbia", "time_zone": "Africa/Tripoli", "city": "Trípoli" },
    { "country_code": "MA", "country_name": "Marrocos", "time_zone": "Africa/Casablanca", "city": "Casablanca" },
    { "country_code": "MC", "country_name": "Mônaco", "time_zone": "Europe/Monaco", "city": "Mônaco" },
    { "country_code": "MD", "country_name": "Moldávia", "time_zone": "Europe/Chisinau", "city": "Chisinau" },
    { "country_code": "MG", "country_name": "Madagáscar", "time_zone": "Indian/Antananarivo", "city": "Antananarivo" },
    { "country_code": "MK", "country_name": "Macedônia", "time_zone": "Europe/Skopje", "city": "Skopje" },
    { "country_code": "MM", "country_name": "Mianmar", "time_zone": "Asia/Yangon", "city": "Yangon" },
    { "country_code": "MN", "country_name": "Mongólia", "time_zone": "Asia/Ulaanbaatar", "city": "Ulaanbaatar" },
    { "country_code": "MO", "country_name": "Macau", "time_zone": "Asia/Macau", "city": "Macau" },
    { "country_code": "MT", "country_name": "Malta", "time_zone": "Europe/Malta", "city": "Malta" },
    { "country_code": "MU", "country_name": "Maurício", "time_zone": "Indian/Mauritius", "city": "Maurício" },
    { "country_code": "MV", "country_name": "Maldivas", "time_zone": "Indian/Maldives", "city": "Maldivas" },
    { "country_code": "MX", "country_name": "México", "time_zone": "America/Mexico_City", "city": "Cidade do México" },
    { "country_code": "MY", "country_name": "Malásia", "time_zone": "Asia/Kuala_Lumpur", "city": "Kuala Lumpur" },
    { "country_code": "NA", "country_name": "Namíbia", "time_zone": "Africa/Windhoek", "city": "Windhoek" },
    { "country_code": "NC", "country_name": "Nova Caledônia", "time_zone": "Pacific/Noumea", "city": "Nouméa" },
    { "country_code": "NG", "country_name": "Nigéria", "time_zone": "Africa/Lagos", "city": "Lagos" },
    { "country_code": "NI", "country_name": "Nicarágua", "time_zone": "America/Managua", "city": "Manágua" },
    { "country_code": "NL", "country_name": "Países Baixos", "time_zone": "Europe/Amsterdam", "city": "Amsterdã" },
    { "country_code": "NO", "country_name": "Noruega", "time_zone": "Europe/Oslo", "city": "Oslo" },
    { "country_code": "NP", "country_name": "Nepal", "time_zone": "Asia/Kathmandu", "city": "Catmandu" },
    { "country_code": "NR", "country_name": "Nauru", "time_zone": "Pacific/Nauru", "city": "Nauru" },
    { "country_code": "NZ", "country_name": "Nova Zelândia", "time_zone": "Pacific/Auckland", "city": "Auckland" },
    { "country_code": "OM", "country_name": "Omã", "time_zone": "Asia/Muscat", "city": "Mascate" },
    { "country_code": "PA", "country_name": "Panamá", "time_zone": "America/Panama", "city": "Panamá" },
    { "country_code": "PE", "country_name": "Peru", "time_zone": "America/Lima", "city": "Lima" },
    { "country_code": "PG", "country_name": "Papua-Nova Guiné", "time_zone": "Pacific/Port_Moresby", "city": "Port Moresby" },
    { "country_code": "PH", "country_name": "Filipinas", "time_zone": "Asia/Manila", "city": "Manila" },
    { "country_code": "PK", "country_name": "Paquistão", "time_zone": "Asia/Karachi", "city": "Carachi" },
    { "country_code": "PL", "country_name": "Polônia", "time_zone": "Europe/Warsaw", "city": "Varsóvia" },
    { "country_code": "PR", "country_name": "Porto Rico", "time_zone": "America/Puerto_Rico", "city": "Porto Rico" },
    { "country_code": "PS", "country_name": "Território Palestino", "time_zone": "Asia/Gaza", "city": "Gaza" },
    { "country_code": "PT", "country_name": "Portugal", "time_zone": "Europe/Lisbon", "city": "Lisboa" },
    { "country_code": "PY", "country_name": "Paraguai", "time_zone": "America/Asuncion", "city": "Assunção" },
    { "country_code": "QA", "country_name": "Catar", "time_zone": "Asia/Qatar", "city": "Catar" },
    { "country_code": "RO", "country_name": "Romênia", "time_zone": "Europe/Bucharest", "city": "Bucareste" },
    { "country_code": "RS", "country_name": "Sérvia", "time_zone": "Europe/Belgrade", "city": "Belgrado" },
    { "country_code": "SA", "country_name": "Arábia Saudita", "time_zone": "Asia/Riyadh", "city": "Riade" },
    { "country_code": "SB", "country_name": "Ilhas Salomão", "time_zone": "Pacific/Guadalcanal", "city": "Guadalcanal" },
    { "country_code": "SE", "country_name": "Suécia", "time_zone": "Europe/Stockholm", "city": "Estocolmo" },
    { "country_code": "SG", "country_name": "Singapura", "time_zone": "Asia/Singapore", "city": "Singapura" },
    { "country_code": "SI", "country_name": "Eslovênia", "time_zone": "Europe/Ljubljana", "city": "Liubliana" },
    { "country_code": "SK", "country_name": "Eslováquia", "time_zone": "Europe/Bratislava", "city": "Bratislava" },
    { "country_code": "SR", "country_name": "Suriname", "time_zone": "America/Paramaribo", "city": "Paramaribo" },
    { "country_code": "SV", "country_name": "El Salvador", "time_zone": "America/El_Salvador", "city": "El Salvador" },
    { "country_code": "SY", "country_name": "Síria", "time_zone": "Asia/Damascus", "city": "Damasco" },
    { "country_code": "TH", "country_name": "Tailândia", "time_zone": "Asia/Bangkok", "city": "Bangkok" },
    { "country_code": "TJ", "country_name": "Tajiquistão", "time_zone": "Asia/Dushanbe", "city": "Duchambe" },
    { "country_code": "TM", "country_name": "Turcomenistão", "time_zone": "Asia/Ashgabat", "city": "Ashgabat" },
    { "country_code": "TN", "country_name": "Tunísia", "time_zone": "Africa/Tunis", "city": "Túnis" },
    { "country_code": "TO", "country_name": "Tonga", "time_zone": "Pacific/Tongatapu", "city": "Tongatapu" },
    { "country_code": "TR", "country_name": "Turquia", "time_zone": "Europe/Istanbul", "city": "Istambul" },
    { "country_code": "TT", "country_name": "Trinidad e Tobago", "time_zone": "America/Port_of_Spain", "city": "Porto de Espanha" },
    { "country_code": "TW", "country_name": "Taiwan", "time_zone": "Asia/Taipei", "city": "Taipé" },
    { "country_code": "TZ", "country_name": "Tanzânia", "time_zone": "Africa/Dar_es_Salaam", "city": "Dar es Salaam" },
    { "country_code": "UA", "country_name": "Ucrânia", "time_zone": "Europe/Kiev", "city": "Kiev" },
    { "country_code": "UG", "country_name": "Uganda", "time_zone": "Africa/Kampala", "city": "Kampala" },
    { "country_code": "UY", "country_name": "Uruguai", "time_zone": "America/Montevideo", "city": "Montevidéu" },
    { "country_code": "UZ", "country_name": "Uzbequistão", "time_zone": "Asia/Tashkent", "city": "Tashkent" },
    { "country_code": "VE", "country_name": "Venezuela", "time_zone": "America/Caracas", "city": "Caracas" },
    { "country_code": "VN", "country_name": "Vietnã", "time_zone": "Asia/Ho_Chi_Minh", "city": "Ho Chi Minh" },
    { "country_code": "WS", "country_name": "Samoa", "time_zone": "Pacific/Apia", "city": "Apia" },
    { "country_code": "YE", "country_name": "Iêmen", "time_zone": "Asia/Aden", "city": "Áden" },
    { "country_code": "ZA", "country_name": "África do Sul", "time_zone": "Africa/Johannesburg", "city": "Joanesburgo" },
    { "country_code": "ZW", "country_name": "Zimbábue", "time_zone": "Africa/Harare", "city": "Harare" }
];

