// Global variable for country/timezone data
const countryTimezonesData = [
    { "country_code": "US", "country_name": "United States", "time_zone": "America/New_York", "city": "New York" },
    { "country_code": "US", "country_name": "United States", "time_zone": "America/Chicago", "city": "Chicago" },
    { "country_code": "US", "country_name": "United States", "time_zone": "America/Denver", "city": "Denver" },
    { "country_code": "US", "country_name": "United States", "time_zone": "America/Los_Angeles", "city": "Los Angeles" },
    { "country_code": "US", "country_name": "United States", "time_zone": "America/Anchorage", "city": "Anchorage" },
    { "country_code": "US", "country_name": "United States", "time_zone": "Pacific/Honolulu", "city": "Honolulu" },
    { "country_code": "US", "country_name": "United States", "time_zone": "America/Phoenix", "city": "Phoenix" },
    { "country_code": "US", "country_name": "United States", "time_zone": "America/Detroit", "city": "Detroit" },
    { "country_code": "AU", "country_name": "Australia", "time_zone": "Australia/Sydney", "city": "Sydney" },
    { "country_code": "AU", "country_name": "Australia", "time_zone": "Australia/Melbourne", "city": "Melbourne" },
    { "country_code": "AU", "country_name": "Australia", "time_zone": "Australia/Brisbane", "city": "Brisbane" },
    { "country_code": "AU", "country_name": "Australia", "time_zone": "Australia/Perth", "city": "Perth" },
    { "country_code": "AU", "country_name": "Australia", "time_zone": "Australia/Adelaide", "city": "Adelaide" },
    { "country_code": "AU", "country_name": "Australia", "time_zone": "Australia/Hobart", "city": "Hobart" },
    { "country_code": "AU", "country_name": "Australia", "time_zone": "Australia/Darwin", "city": "Darwin" },
    { "country_code": "ES", "country_name": "Spain", "time_zone": "Europe/Madrid", "city": "Madrid" },
    { "country_code": "ES", "country_name": "Spain", "time_zone": "Atlantic/Canary", "city": "Canary Islands" },
    { "country_code": "ES", "country_name": "Spain", "time_zone": "Africa/Ceuta", "city": "Ceuta" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Europe/Moscow", "city": "Moscow" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Europe/Kaliningrad", "city": "Kaliningrad" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Yekaterinburg", "city": "Yekaterinburg" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Omsk", "city": "Omsk" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Krasnoyarsk", "city": "Krasnoyarsk" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Irkutsk", "city": "Irkutsk" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Yakutsk", "city": "Yakutsk" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Vladivostok", "city": "Vladivostok" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Magadan", "city": "Magadan" },
    { "country_code": "RU", "country_name": "Russia", "time_zone": "Asia/Kamchatka", "city": "Kamchatka" },
    { "country_code": "BR", "country_name": "Brazil", "time_zone": "America/Sao_Paulo", "city": "Sao Paulo" },
    { "country_code": "BR", "country_name": "Brazil", "time_zone": "America/Manaus", "city": "Manaus" },
    { "country_code": "BR", "country_name": "Brazil", "time_zone": "America/Noronha", "city": "Noronha" },
    { "country_code": "CA", "country_name": "Canada", "time_zone": "America/Toronto", "city": "Toronto" },
    { "country_code": "CA", "country_name": "Canada", "time_zone": "America/Vancouver", "city": "Vancouver" },
    { "country_code": "CA", "country_name": "Canada", "time_zone": "America/Edmonton", "city": "Edmonton" },
    { "country_code": "CA", "country_name": "Canada", "time_zone": "America/Winnipeg", "city": "Winnipeg" },
    { "country_code": "CA", "country_name": "Canada", "time_zone": "America/Halifax", "city": "Halifax" },
    { "country_code": "CA", "country_name": "Canada", "time_zone": "America/St_Johns", "city": "St Johns" },
    { "country_code": "AD", "country_name": "Andorra", "time_zone": "Europe/Andorra", "city": "Andorra" },
    { "country_code": "AE", "country_name": "United Arab Emirates", "time_zone": "Asia/Dubai", "city": "Dubai" },
    { "country_code": "AF", "country_name": "Afghanistan", "time_zone": "Asia/Kabul", "city": "Kabul" },
    { "country_code": "AG", "country_name": "Antigua and Barbuda", "time_zone": "America/Antigua", "city": "Antigua" },
    { "country_code": "AI", "country_name": "Anguilla", "time_zone": "America/Anguilla", "city": "Anguilla" },
    { "country_code": "AL", "country_name": "Albania", "time_zone": "Europe/Tirane", "city": "Tirane" },
    { "country_code": "AM", "country_name": "Armenia", "time_zone": "Asia/Yerevan", "city": "Yerevan" },
    { "country_code": "AO", "country_name": "Angola", "time_zone": "Africa/Luanda", "city": "Luanda" },
    { "country_code": "AQ", "country_name": "Antarctica", "time_zone": "Antarctica/McMurdo", "city": "McMurdo Station" },
    { "country_code": "AQ", "country_name": "Antarctica", "time_zone": "Antarctica/Casey", "city": "Casey Station" },
    { "country_code": "AQ", "country_name": "Antarctica", "time_zone": "Antarctica/Davis", "city": "Davis Station" },
    { "country_code": "AR", "country_name": "Argentina", "time_zone": "America/Argentina/Buenos_Aires", "city": "Buenos Aires" },
    { "country_code": "AS", "country_name": "American Samoa", "time_zone": "Pacific/Pago_Pago", "city": "Pago Pago" },
    { "country_code": "AT", "country_name": "Austria", "time_zone": "Europe/Vienna", "city": "Vienna" },
    { "country_code": "AW", "country_name": "Aruba", "time_zone": "America/Aruba", "city": "Aruba" },
    { "country_code": "AZ", "country_name": "Azerbaijan", "time_zone": "Asia/Baku", "city": "Baku" },
    { "country_code": "BA", "country_name": "Bosnia and Herzegovina", "time_zone": "Europe/Sarajevo", "city": "Sarajevo" },
    { "country_code": "BB", "country_name": "Barbados", "time_zone": "America/Barbados", "city": "Barbados" },
    { "country_code": "BD", "country_name": "Bangladesh", "time_zone": "Asia/Dhaka", "city": "Dhaka" },
    { "country_code": "BE", "country_name": "Belgium", "time_zone": "Europe/Brussels", "city": "Brussels" },
    { "country_code": "BG", "country_name": "Bulgaria", "time_zone": "Europe/Sofia", "city": "Sofia" },
    { "country_code": "BH", "country_name": "Bahrain", "time_zone": "Asia/Bahrain", "city": "Bahrain" },
    { "country_code": "BM", "country_name": "Bermuda", "time_zone": "Atlantic/Bermuda", "city": "Bermuda" },
    { "country_code": "BN", "country_name": "Brunei", "time_zone": "Asia/Brunei", "city": "Brunei" },
    { "country_code": "BO", "country_name": "Bolivia", "time_zone": "America/La_Paz", "city": "La Paz" },
    { "country_code": "BS", "country_name": "Bahamas", "time_zone": "America/Nassau", "city": "Nassau" },
    { "country_code": "BT", "country_name": "Bhutan", "time_zone": "Asia/Thimphu", "city": "Thimphu" },
    { "country_code": "BW", "country_name": "Botswana", "time_zone": "Africa/Gaborone", "city": "Gaborone" },
    { "country_code": "BY", "country_name": "Belarus", "time_zone": "Europe/Minsk", "city": "Minsk" },
    { "country_code": "BZ", "country_name": "Belize", "time_zone": "America/Belize", "city": "Belize" },
    { "country_code": "CD", "country_name": "Democratic Republic of the Congo", "time_zone": "Africa/Kinshasa", "city": "Kinshasa" },
    { "country_code": "CF", "country_name": "Central African Republic", "time_zone": "Africa/Bangui", "city": "Bangui" },
    { "country_code": "CH", "country_name": "Switzerland", "time_zone": "Europe/Zurich", "city": "Zurich" },
    { "country_code": "CI", "country_name": "Ivory Coast", "time_zone": "Africa/Abidjan", "city": "Abidjan" },
    { "country_code": "CK", "country_name": "Cook Islands", "time_zone": "Pacific/Rarotonga", "city": "Rarotonga" },
    { "country_code": "CL", "country_name": "Chile", "time_zone": "America/Santiago", "city": "Santiago" },
    { "country_code": "CL", "country_name": "Chile", "time_zone": "Pacific/Easter", "city": "Easter Island" },
    { "country_code": "CM", "country_name": "Cameroon", "time_zone": "Africa/Douala", "city": "Douala" },
    { "country_code": "CN", "country_name": "China", "time_zone": "Asia/Shanghai", "city": "Shanghai" },
    { "country_code": "CO", "country_name": "Colombia", "time_zone": "America/Bogota", "city": "Bogota" },
    { "country_code": "CR", "country_name": "Costa Rica", "time_zone": "America/Costa_Rica", "city": "Costa Rica" },
    { "country_code": "CU", "country_name": "Cuba", "time_zone": "America/Havana", "city": "Havana" },
    { "country_code": "CV", "country_name": "Cape Verde", "time_zone": "Atlantic/Cape_Verde", "city": "Cape Verde" },
    { "country_code": "CY", "country_name": "Cyprus", "time_zone": "Asia/Nicosia", "city": "Nicosia" },
    { "country_code": "CZ", "country_name": "Czech Republic", "time_zone": "Europe/Prague", "city": "Prague" },
    { "country_code": "DE", "country_name": "Germany", "time_zone": "Europe/Berlin", "city": "Berlin" },
    { "country_code": "DK", "country_name": "Denmark", "time_zone": "Europe/Copenhagen", "city": "Copenhagen" },
    { "country_code": "DO", "country_name": "Dominican Republic", "time_zone": "America/Santo_Domingo", "city": "Santo Domingo" },
    { "country_code": "DZ", "country_name": "Algeria", "time_zone": "Africa/Algiers", "city": "Algiers" },
    { "country_code": "EC", "country_name": "Ecuador", "time_zone": "America/Guayaquil", "city": "Guayaquil" },
    { "country_code": "EC", "country_name": "Ecuador", "time_zone": "Pacific/Galapagos", "city": "Galapagos" },
    { "country_code": "EE", "country_name": "Estonia", "time_zone": "Europe/Tallinn", "city": "Tallinn" },
    { "country_code": "EG", "country_name": "Egypt", "time_zone": "Africa/Cairo", "city": "Cairo" },
    { "country_code": "FI", "country_name": "Finland", "time_zone": "Europe/Helsinki", "city": "Helsinki" },
    { "country_code": "FJ", "country_name": "Fiji", "time_zone": "Pacific/Fiji", "city": "Fiji" },
    { "country_code": "FK", "country_name": "Falkland Islands", "time_zone": "Atlantic/Stanley", "city": "Stanley" },
    { "country_code": "FR", "country_name": "France", "time_zone": "Europe/Paris", "city": "Paris" },
    { "country_code": "GB", "country_name": "United Kingdom", "time_zone": "Europe/London", "city": "London" },
    { "country_code": "GE", "country_name": "Georgia", "time_zone": "Asia/Tbilisi", "city": "Tbilisi" },
    { "country_code": "GF", "country_name": "French Guiana", "time_zone": "America/Cayenne", "city": "Cayenne" },
    { "country_code": "GH", "country_name": "Ghana", "time_zone": "Africa/Accra", "city": "Accra" },
    { "country_code": "GL", "country_name": "Greenland", "time_zone": "America/Godthab", "city": "Nuuk" },
    { "country_code": "GR", "country_name": "Greece", "time_zone": "Europe/Athens", "city": "Athens" },
    { "country_code": "GT", "country_name": "Guatemala", "time_zone": "America/Guatemala", "city": "Guatemala" },
    { "country_code": "GY", "country_name": "Guyana", "time_zone": "America/Guyana", "city": "Guyana" },
    { "country_code": "HK", "country_name": "Hong Kong", "time_zone": "Asia/Hong_Kong", "city": "Hong Kong" },
    { "country_code": "HN", "country_name": "Honduras", "time_zone": "America/Tegucigalpa", "city": "Tegucigalpa" },
    { "country_code": "HR", "country_name": "Croatia", "time_zone": "Europe/Zagreb", "city": "Zagreb" },
    { "country_code": "HT", "country_name": "Haiti", "time_zone": "America/Port-au-Prince", "city": "Port-au-Prince" },
    { "country_code": "HU", "country_name": "Hungary", "time_zone": "Europe/Budapest", "city": "Budapest" },
    { "country_code": "ID", "country_name": "Indonesia", "time_zone": "Asia/Jakarta", "city": "Jakarta" },
    { "country_code": "IE", "country_name": "Ireland", "time_zone": "Europe/Dublin", "city": "Dublin" },
    { "country_code": "IL", "country_name": "Israel", "time_zone": "Asia/Jerusalem", "city": "Jerusalem" },
    { "country_code": "IN", "country_name": "India", "time_zone": "Asia/Kolkata", "city": "Kolkata" },
    { "country_code": "IQ", "country_name": "Iraq", "time_zone": "Asia/Baghdad", "city": "Baghdad" },
    { "country_code": "IR", "country_name": "Iran", "time_zone": "Asia/Tehran", "city": "Tehran" },
    { "country_code": "IS", "country_name": "Iceland", "time_zone": "Atlantic/Reykjavik", "city": "Reykjavik" },
    { "country_code": "IT", "country_name": "Italy", "time_zone": "Europe/Rome", "city": "Rome" },
    { "country_code": "JM", "country_name": "Jamaica", "time_zone": "America/Jamaica", "city": "Jamaica" },
    { "country_code": "JO", "country_name": "Jordan", "time_zone": "Asia/Amman", "city": "Amman" },
    { "country_code": "JP", "country_name": "Japan", "time_zone": "Asia/Tokyo", "city": "Tokyo" },
    { "country_code": "KE", "country_name": "Kenya", "time_zone": "Africa/Nairobi", "city": "Nairobi" },
    { "country_code": "KG", "country_name": "Kyrgyzstan", "time_zone": "Asia/Bishkek", "city": "Bishkek" },
    { "country_code": "KH", "country_name": "Cambodia", "time_zone": "Asia/Phnom_Penh", "city": "Phnom Penh" },
    { "country_code": "KI", "country_name": "Kiribati", "time_zone": "Pacific/Tarawa", "city": "Tarawa" },
    { "country_code": "KI", "country_name": "Kiribati", "time_zone": "Pacific/Kiritimati", "city": "Kiritimati" },
    { "country_code": "KP", "country_name": "North Korea", "time_zone": "Asia/Pyongyang", "city": "Pyongyang" },
    { "country_code": "KR", "country_name": "South Korea", "time_zone": "Asia/Seoul", "city": "Seoul" },
    { "country_code": "KW", "country_name": "Kuwait", "time_zone": "Asia/Kuwait", "city": "Kuwait" },
    { "country_code": "KZ", "country_name": "Kazakhstan", "time_zone": "Asia/Almaty", "city": "Almaty" },
    { "country_code": "LB", "country_name": "Lebanon", "time_zone": "Asia/Beirut", "city": "Beirut" },
    { "country_code": "LK", "country_name": "Sri Lanka", "time_zone": "Asia/Colombo", "city": "Colombo" },
    { "country_code": "LR", "country_name": "Liberia", "time_zone": "Africa/Monrovia", "city": "Monrovia" },
    { "country_code": "LT", "country_name": "Lithuania", "time_zone": "Europe/Vilnius", "city": "Vilnius" },
    { "country_code": "LU", "country_name": "Luxembourg", "time_zone": "Europe/Luxembourg", "city": "Luxembourg" },
    { "country_code": "LV", "country_name": "Latvia", "time_zone": "Europe/Riga", "city": "Riga" },
    { "country_code": "LY", "country_name": "Libya", "time_zone": "Africa/Tripoli", "city": "Tripoli" },
    { "country_code": "MA", "country_name": "Morocco", "time_zone": "Africa/Casablanca", "city": "Casablanca" },
    { "country_code": "MC", "country_name": "Monaco", "time_zone": "Europe/Monaco", "city": "Monaco" },
    { "country_code": "MD", "country_name": "Moldova", "time_zone": "Europe/Chisinau", "city": "Chisinau" },
    { "country_code": "MG", "country_name": "Madagascar", "time_zone": "Indian/Antananarivo", "city": "Antananarivo" },
    { "country_code": "MK", "country_name": "Macedonia", "time_zone": "Europe/Skopje", "city": "Skopje" },
    { "country_code": "MM", "country_name": "Myanmar", "time_zone": "Asia/Yangon", "city": "Yangon" },
    { "country_code": "MN", "country_name": "Mongolia", "time_zone": "Asia/Ulaanbaatar", "city": "Ulaanbaatar" },
    { "country_code": "MO", "country_name": "Macao", "time_zone": "Asia/Macau", "city": "Macau" },
    { "country_code": "MT", "country_name": "Malta", "time_zone": "Europe/Malta", "city": "Malta" },
    { "country_code": "MU", "country_name": "Mauritius", "time_zone": "Indian/Mauritius", "city": "Mauritius" },
    { "country_code": "MV", "country_name": "Maldives", "time_zone": "Indian/Maldives", "city": "Maldives" },
    { "country_code": "MX", "country_name": "Mexico", "time_zone": "America/Mexico_City", "city": "Mexico City" },
    { "country_code": "MY", "country_name": "Malaysia", "time_zone": "Asia/Kuala_Lumpur", "city": "Kuala Lumpur" },
    { "country_code": "NA", "country_name": "Namibia", "time_zone": "Africa/Windhoek", "city": "Windhoek" },
    { "country_code": "NC", "country_name": "New Caledonia", "time_zone": "Pacific/Noumea", "city": "Noumea" },
    { "country_code": "NG", "country_name": "Nigeria", "time_zone": "Africa/Lagos", "city": "Lagos" },
    { "country_code": "NI", "country_name": "Nicaragua", "time_zone": "America/Managua", "city": "Managua" },
    { "country_code": "NL", "country_name": "Netherlands", "time_zone": "Europe/Amsterdam", "city": "Amsterdam" },
    { "country_code": "NO", "country_name": "Norway", "time_zone": "Europe/Oslo", "city": "Oslo" },
    { "country_code": "NP", "country_name": "Nepal", "time_zone": "Asia/Kathmandu", "city": "Kathmandu" },
    { "country_code": "NR", "country_name": "Nauru", "time_zone": "Pacific/Nauru", "city": "Nauru" },
    { "country_code": "NZ", "country_name": "New Zealand", "time_zone": "Pacific/Auckland", "city": "Auckland" },
    { "country_code": "OM", "country_name": "Oman", "time_zone": "Asia/Muscat", "city": "Muscat" },
    { "country_code": "PA", "country_name": "Panama", "time_zone": "America/Panama", "city": "Panama" },
    { "country_code": "PE", "country_name": "Peru", "time_zone": "America/Lima", "city": "Lima" },
    { "country_code": "PG", "country_name": "Papua New Guinea", "time_zone": "Pacific/Port_Moresby", "city": "Port Moresby" },
    { "country_code": "PH", "country_name": "Philippines", "time_zone": "Asia/Manila", "city": "Manila" },
    { "country_code": "PK", "country_name": "Pakistan", "time_zone": "Asia/Karachi", "city": "Karachi" },
    { "country_code": "PL", "country_name": "Poland", "time_zone": "Europe/Warsaw", "city": "Warsaw" },
    { "country_code": "PR", "country_name": "Puerto Rico", "time_zone": "America/Puerto_Rico", "city": "Puerto Rico" },
    { "country_code": "PS", "country_name": "Palestinian Territory", "time_zone": "Asia/Gaza", "city": "Gaza" },
    { "country_code": "PT", "country_name": "Portugal", "time_zone": "Europe/Lisbon", "city": "Lisbon" },
    { "country_code": "PY", "country_name": "Paraguay", "time_zone": "America/Asuncion", "city": "Asuncion" },
    { "country_code": "QA", "country_name": "Qatar", "time_zone": "Asia/Qatar", "city": "Qatar" },
    { "country_code": "RO", "country_name": "Romania", "time_zone": "Europe/Bucharest", "city": "Bucharest" },
    { "country_code": "RS", "country_name": "Serbia", "time_zone": "Europe/Belgrade", "city": "Belgrade" },
    { "country_code": "SA", "country_name": "Saudi Arabia", "time_zone": "Asia/Riyadh", "city": "Riyadh" },
    { "country_code": "SB", "country_name": "Solomon Islands", "time_zone": "Pacific/Guadalcanal", "city": "Guadalcanal" },
    { "country_code": "SE", "country_name": "Sweden", "time_zone": "Europe/Stockholm", "city": "Stockholm" },
    { "country_code": "SG", "country_name": "Singapore", "time_zone": "Asia/Singapore", "city": "Singapore" },
    { "country_code": "SI", "country_name": "Slovenia", "time_zone": "Europe/Ljubljana", "city": "Ljubljana" },
    { "country_code": "SK", "country_name": "Slovakia", "time_zone": "Europe/Bratislava", "city": "Bratislava" },
    { "country_code": "SR", "country_name": "Suriname", "time_zone": "America/Paramaribo", "city": "Paramaribo" },
    { "country_code": "SV", "country_name": "El Salvador", "time_zone": "America/El_Salvador", "city": "El Salvador" },
    { "country_code": "SY", "country_name": "Syria", "time_zone": "Asia/Damascus", "city": "Damascus" },
    { "country_code": "TH", "country_name": "Thailand", "time_zone": "Asia/Bangkok", "city": "Bangkok" },
    { "country_code": "TJ", "country_name": "Tajikistan", "time_zone": "Asia/Dushanbe", "city": "Dushanbe" },
    { "country_code": "TM", "country_name": "Turkmenistan", "time_zone": "Asia/Ashgabat", "city": "Ashgabat" },
    { "country_code": "TN", "country_name": "Tunisia", "time_zone": "Africa/Tunis", "city": "Tunis" },
    { "country_code": "TO", "country_name": "Tonga", "time_zone": "Pacific/Tongatapu", "city": "Tongatapu" },
    { "country_code": "TR", "country_name": "Turkey", "time_zone": "Europe/Istanbul", "city": "Istanbul" },
    { "country_code": "TT", "country_name": "Trinidad and Tobago", "time_zone": "America/Port_of_Spain", "city": "Port of Spain" },
    { "country_code": "TW", "country_name": "Taiwan", "time_zone": "Asia/Taipei", "city": "Taipei" },
    { "country_code": "TZ", "country_name": "Tanzania", "time_zone": "Africa/Dar_es_Salaam", "city": "Dar es Salaam" },
    { "country_code": "UA", "country_name": "Ukraine", "time_zone": "Europe/Kiev", "city": "Kiev" },
    { "country_code": "UG", "country_name": "Uganda", "time_zone": "Africa/Kampala", "city": "Kampala" },
    { "country_code": "UY", "country_name": "Uruguay", "time_zone": "America/Montevideo", "city": "Montevideo" },
    { "country_code": "UZ", "country_name": "Uzbekistan", "time_zone": "Asia/Tashkent", "city": "Tashkent" },
    { "country_code": "VE", "country_name": "Venezuela", "time_zone": "America/Caracas", "city": "Caracas" },
    { "country_code": "VN", "country_name": "Vietnam", "time_zone": "Asia/Ho_Chi_Minh", "city": "Ho Chi Minh" },
    { "country_code": "WS", "country_name": "Samoa", "time_zone": "Pacific/Apia", "city": "Apia" },
    { "country_code": "YE", "country_name": "Yemen", "time_zone": "Asia/Aden", "city": "Aden" },
    { "country_code": "ZA", "country_name": "South Africa", "time_zone": "Africa/Johannesburg", "city": "Johannesburg" },
    { "country_code": "ZW", "country_name": "Zimbabwe", "time_zone": "Africa/Harare", "city": "Harare" }
];

